name: Ke toan FE to Cpanel
on:
    push:
        branches:
            - dev_fe_ketoan
jobs:
    FTP-Deploy-Action:
        name: FTP-Deploy-Action
        runs-on: ubuntu-latest
        steps:
        - uses : actions/checkout@v2.1.0
          with:
            fetch-depth: 2
        - name: FTP-Deploy-Action
          uses: SamKirkland/FTP-Deploy-Action@3.1.1
          with:
            ftp-server: 'hf44-22061.azdigihost.com'
            ftp-username: 'chikiet@chikiet.com'
            ftp-password: '@Hikiet1988'